# Generated by Django 6.0.5 on 2026-05-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Uncategorized', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='modify_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='modify_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(),
        ),
    ]
